# NOTE: this is the production Docker Compose configuration file. DO NOT put
#       any stuff that must be available only in development. Please use the
#       file docker-compose.override.yml instead.
version: "2"
services:
  swarm-logger:
    build: ./mu-swarm-logger-service
    links:
      - database:database
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: /src/run.py --debug sparql
  database:
    image: tenforce/virtuoso:1.1.1-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
  event-query:
    build: ./mu-docker-event-query
    links:
      - database:database
    volumes:
      - ./containers:/usr/src/app/containers/
      - ./mu-docker-event-query/src:/app/
    environment:
      SLEEP_PERIOD: '10'
  har-transformation:
    build: ./mu-har-transformation
    volumes:
      - ./pcap:/app/pcap
      - ./har:/app/har
      - ./containers:/app/containers
    links:
      - elasticsearch:elasticsearch
  elasticsearch:
    image: elasticsearch:2
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
  kibana:
    image: kibana:4
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch:elasticsearch
